car_companies = [
    "Toyota",
    "Honda",
    "Ford",
    "Chevrolet",
    "Volkswagen",
    "BMW",
    "Mercedes-Benz",
    "Audi",
    "Tesla",
    "Nissan",
    "Hyundai",
    "Kia",
    "Volvo",
    "Subaru",
    "Mazda",
    "Lexus",
    "Jeep",
    "Ferrari",
    "Porsche",
    "Mitsubishi",
    "Buick",
    "Chrysler",
    "Land Rover",
    "Jaguar",
    "Cadillac",
    "Lincoln",
    "GMC",
    "Acura",
    "Infiniti",
    "Mini",
    "Alfa Romeo",
    "Bentley",
    "Maserati",
    "McLaren",
    "Fiat",
    "Ram",
    "Genesis",
    "Smart",
    "Bugatti",
    "Pagani",
    "Koenigsegg",
    "Maybach",
    "Dodge",
    "Suzuki",
    "Rolls-Royce",
    "Aston Martin",
    "Lamborghini",
    "Lotus",
    "Ariel",
    "Karma",
    "Rivian",
    "Lucid Motors",
    "Byton",
    "Faraday Future",
    "Rimac",
    "Bollinger",
    "Canoo",
    "Fisker",
    "Lordstown Motors",
    "Rivian"
]
